(
    SELECT substring(SALES_DATE, 1, 10) AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE SALES_DATE >= "2022-03-01" AND SALES_DATE < "2022-04-01"
)
UNION ALL
(
    SELECT substring(SALES_DATE, 1, 10) AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE SALES_DATE >= "2022-03-01" AND SALES_DATE < "2022-04-01"
)
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
