SELECT MEMBER_ID, MEMBER_NAME, GENDER, substring(DATE_OF_BIRTH, 1, 10) AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE substring(DATE_OF_BIRTH,6,2) = "03" AND GENDER = 'W' and TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC
